# Generated by Django 3.1.5 on 2021-03-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrimp', '0002_auto_20210304_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='userid',
            field=models.BigIntegerField(verbose_name='回答者在User表中的id'),
        ),
    ]
