# Generated by Django 3.1.5 on 2021-03-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrimp', '0003_auto_20210304_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='url_token',
            field=models.CharField(max_length=100, verbose_name='用户的唯一标识'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='answer_id',
            field=models.IntegerField(verbose_name='回答的id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='other_userid',
            field=models.BigIntegerField(verbose_name='回复者在User表中的id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.BigIntegerField(verbose_name='评论者在User表中的id'),
        ),
        migrations.AlterField(
            model_name='question',
            name='userid',
            field=models.IntegerField(verbose_name='用户id'),
        ),
    ]
